language: node_js
node_js:
- 0.12

# Use Travis' new container-based running system.
sudo: false

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

addons:
  firefox: "latest"

install:
- npm install -g babel-cli
- npm install
